// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGBDgsyG7_25e2A6hnsStkPkaazWhHIPs',
    appId: '1:94862128843:web:e8f92728502955585e8d4e',
    messagingSenderId: '94862128843',
    projectId: 'study-app-2ade9',
    authDomain: 'study-app-2ade9.firebaseapp.com',
    storageBucket: 'study-app-2ade9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XLopQjArOUw62DxhTEAEecmhPmeaph8',
    appId: '1:94862128843:android:b793460df76070115e8d4e',
    messagingSenderId: '94862128843',
    projectId: 'study-app-2ade9',
    storageBucket: 'study-app-2ade9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoM4rI9S3GlW_QxgiJSJkkbI01jTHJnP0',
    appId: '1:94862128843:ios:0c815d637a881b8b5e8d4e',
    messagingSenderId: '94862128843',
    projectId: 'study-app-2ade9',
    storageBucket: 'study-app-2ade9.appspot.com',
    iosClientId: '94862128843-vm6o24bgmm260vamne4r6llbbnoeu6ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoM4rI9S3GlW_QxgiJSJkkbI01jTHJnP0',
    appId: '1:94862128843:ios:a2ad7ab96a7cc3395e8d4e',
    messagingSenderId: '94862128843',
    projectId: 'study-app-2ade9',
    storageBucket: 'study-app-2ade9.appspot.com',
    iosClientId: '94862128843-ucnvbrp8j78l3j57mula726m89clqhp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp.RunnerTests',
  );
}
